# Using trusty because the Travis Addon for SonarQube.com requires Java 8
dist: trusty
sudo: required

language: node_js
node_js:
  - 10

addons:
  sonarcloud:
    organization: syquel-github
    token:
      secure: "vjrx+JqjNmc14CiUTp3Emtruxde5QUPGwZNvYuZcWIobOM/JbtSIIx6GHNsxOKY6lgn0hAZVayZPd8aUaONEYWOm5R0N/lxatey5o+bU05KANAZ7faJTShQVMvUQeLYxU2SNfJFPThTjVGuDkUeZK9XsOWaQ2MMa2R7pltnUzxsqf9oQaw6lgvc9rVf6wxxbqeq8lbGqXkdH4vTzPFDTJdoMkm2cphBOy7w0gnwKpJk4HQjzbU+8d/IjR3afEsr34JN/b0RkVN96mcV80aPx7M8CXiar9f8tvJhpnbUOHzHHaBQB12vouj6GtIbAivlff4If8viJweK8c6twbNslUHFPXaik4k2Olti7dUj2cg/w/92wc2AxiCDv5ygx5Z4Q0es5qE1R9pZpEepCe8Wt8Pi0+HJe9lDf3iXU6EsMXhE7EBM9HLMMwzZT0V7JpHqMTfj6Gt8HuGeZpJkhz/ynJEJlbPCQb2rlzR4rWWBZODx5F27oxwO79qc78VyM3XpERd/6rcaQuW2RZWgTMwuU+u9UlgAjpKGYg21jMoyjBwLPuR7umSR4FCQ7NqiCYphLhwOU0vQwFxYOYm0Mmrj1VTZhbbvVyPIRVii9hLmqAPrtcwUsnvIfgLF1gMU2ozbJyIA/jwt+MrLcTgT88JSdOp9uLW9mMBsB0Jpoum8Pm0k="

install: npm ci

# Actually calls Gulp - the SonarQube analysis is the default task
script: npx gulp

cache: npm

deploy:
  provider: npm
  api_key:
    secure: jxFoUX7a7T4oLNplJ0CxwAg2TzQzpsINHxB4scVuHtpDYcfKoB2fnTtMEy1xRY1j8rXLyIC1XggngBHBwSK4pHmreGJ0m0acGZEfj1xF6cf8jy4pOcHkDKWk6IIOrnqCSfsXaYidu6/8qcFMHKZBTpwrzRlmtDYPtxfs4dqvv56WQCyaLdquwSJVGRJw/ZhkI8pIRo2ZelfQDluoRd7pPn0MGEJE42f8EEiM30nD0Iq1r6KKKIAZMp12arGKKuhXizP5FRbWbJkUwY/HAy3Hibg6k9YB2u2J7CXzvtH9UCEArjLg6DPoO2B1bN8WbfVn8LXWqhPdsrS9YzCjHMq4jaaq5wI2oAWWm7q/NIDvrw55z91CwTuErXJnZR5ThX+GE6lZ4F2W54pqHK43sEImbvQNLF7GcHUzqR/SaA1FebdPwh9KhafdSCT1famkQc/jV49p76V3WB/N372GI+rte+GMqxHPazlAAziqSJozVfIBrhnXwJvWylB3ORFrPoMtkt82jzSkmj4QEk1t4o/UFRr6JGVLhnvlXRGeKJZMEwWQCRVt/p2Zian7swmF/vZH+K+rZewQaZfe6fED0eu9C2yNotiuzqUg+DG9ayDNE/bPy4Ot8NVzbUKvQ3fMsdi6q7L/H9mnvguf3BoPaLIazkRLyyGLG9mkXXmXn6QIc54=
  email: frederik.boster@syquel-systems.de
  on:
    tags: true